spring:
  application:
    name: learner-user-api
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    password: Learner@2023
    url: jdbc:mysql://34.29.125.76:3306,34.68.236.8:3306/learnerCrownClothing?useSSL=FALSE
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8232
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8181/eureka/
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    password: Learner@2023
    url: jdbc:mysql://35.188.122.252:3306/learnerCrownClothing?useSSL=FALSE
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://34.29.95.107:8761/eureka/
